name: codelessly_starter
description: "A new codelessly starter project"

publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  codelessly_sdk: ^5.2.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/codelessly_config.json
